# use the latest ubuntu environment (18.04) available on travis
language: go

env: GO15VENDOREXPERIMENT=1

go:
  - tip

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go test -v -covermode=count -race ./...  # Run all the tests with the race detector enabled